add_newline = true
# format = "$directory$line_break$character"
format = "$directory$git_branch$line_break$character"

[character]
# success_symbol = "[λ](bold green)"
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

# [line_break]
# disabled = true

[aws]
disabled = true

[golang]
disabled = true
format = '[ ](bold cyan)'

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
symbol = " "
style = "bold green"

[git_state]
disabled = false

[gcloud]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 5
read_only = " 󰌾"
truncation_symbol = "…/"

[directory.substitutions]
"~/dev/gh/chainguard" = "@cg"
"~/dev/gh/wolfi" = "@wolfi"
"~/dev/gh/joshrwolf" = "@personal"
"~/dev/gh/kabbages-co" = "@lab"

[kubernetes]
disabled = true
symbol = '☸ '

[custom.jj]
command = "prompt"
format = "$output"
ignore_timeout = true
shell = ["starship-jj", "--ignore-working-copy", "starship"]
use_stdin = false
when = true
